<?php
	/**
	 * Render the logs added to the custom log
	 * file
	 *
	 */

	// Block direct access to the file
	if ( ! defined( 'ABSPATH' ) ) {
		exit();
	}
?>
<div class="dse-content dse-grid-item dse-grid-item--fluid dse-grid dse-grid-horizontal">

	<div class="dse-container dse-container-fluid dse-grid-item dse-grid-item-fluid">
		<div class="row">
			<div class="col-md-12">
				<!--begin::Portlet-->

				<div class="dse-box">

					<div class="dse-box-header">
						<div class="dse-box-header-wrapper">
							<h3 class="dse-box-header-title"><?php esc_html_e( 'Plugin\'s Log', 'dropshipexpress' ); ?></h3>
						</div>
					</div>

					<div class="dse-box-body">

						<div class="dse-box-style2">
							<p>
								<?php esc_html_e( 'Here you can check the log that has been generated by the plugin. This information might help your diagnose any possible issues.', 'dropshipexpress' ); ?>
							</p>
						</div>

						<div class="dse-log">
							<pre>
								<code id="dse-log" class="language-php"><?php
										/**
										 * @var $wp_filesystem \WP_Filesystem_Direct
										 */
										global $wp_filesystem;

										if ( WP_Filesystem() && $wp_filesystem->is_file( DSE_LOG_FILE ) ) {

											$log = $wp_filesystem->get_contents( DSE_LOG_FILE );

											if ( FALSE !== $log ) {
												if ( ! empty( $log ) ) {
													echo esc_html( $log );
												} else {
													esc_html_e( 'The log file is empty.', 'dropshipexpress' );
												}
											} else {
												esc_html_e( 'Can not access the log file.', 'dropshipexpress' );
											}
										} else {
											esc_html_e( 'The log file does not exist. Try deactivating and reactivating the plugin, this might fix the issue.', 'dropshipexpress' );
										}
									?></code>
							</pre>
						</div>
					</div>

					<div class="dse-box-footer">
						<form id="dse-log-form" action="<?php echo esc_url( admin_url( 'admin-ajax.php' ) ) ?>" method="post">
							<div class="dse-form-actions dse-form-actions-right">
								<button type="submit" class="btn btn-danger">
									<i class="fa fa-times"></i><?php esc_html_e( 'Clear Log', 'dropshipexpress' ); ?>
								</button>
							</div>
							<input type="hidden" name="action" value="dse_clear_log">
							<?php wp_nonce_field( 'dse_clear_log_nonce_8907', 'dse-clear-log-nonce' ); ?>
						</form>
					</div>

				</div>
				<!--end::Portlet-->
			</div>
		</div>
	</div>
</div>
